fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    concat: https://github.com/puppetlabs/puppetlabs-concat.git
    postgreql: https://github.com/puppetlabs/puppetlabs-postgresql.git
  symlinks:
    pgbouncer: "#{source_dir}"
